
###Posts

###

POST http://localhost:4000/posts
Content-Type: application/json

{
    "title": "second",
    "sender": "677ff5652758ff9eb4710bbb",
    "content": "It will surely work"
}

###

GET http://localhost:4000/posts

###

GET http://localhost:4000/posts?postSender=677ff5652758ff9eb4710bbb

###

GET http://localhost:4000/posts/69738d301f5dd36c46bf37e3

###

PUT http://localhost:4000/posts/69738d301f5dd36c46bf37e3
Content-Type: application/json

{
    "title": "Updated g",
    "sender": "677ff5652758ff9eb4710a1c",
    "content": "Very job"
}

###Comments

###

POST http://localhost:4000/comments
Content-Type: application/json

{
    "user": "677ff5652758ff9eb4710a1c",
    "content": "bla",
    "postId": "69738d301f5dd36c46bf37e3"
}

###

PUT http://localhost:4000/comments/69738ec71f5dd36c46bf37f6
Content-Type: application/json

{
    "content": "content post updating"
}
###

GET http://localhost:4000/comments

###

DELETE http://localhost:4000/comments/69738ec71f5dd36c46bf37f6

###

GET http://localhost:4000/comments/69738ec71f5dd36c46bf37f6

###

GET http://localhost:4000/comments/post/69738d301f5dd36c46bf37e3

