
###Posts###

GET http://localhost:3000/posts

###


POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Beautiful Post",
    "sender": "677ff5652758ff9eb4710bbb",
    "content": "I am happy"
}


###

GET http://localhost:3000/posts/697394c23826c8eaa931bd2a


###

GET http://localhost:3000/posts?postSender=677ff5652758ff9eb4710bbb

###

PUT http://localhost:3000/posts/697394c23826c8eaa931bd2a
Content-Type: application/json

{
    "title": "Updated g",
    "sender": "677ff5652758ff9eb4710a1c",
    "content": "Very job"
}




###Comments###

GET http://localhost:3000/comments

###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "userId": "677ff5652758ff9eb4710a1c",
    "content": "good job!",
    "postId": "697394c23826c8eaa931bd2a"
}

###

PUT http://localhost:3000/comments/697395d63826c8eaa931bd2c
Content-Type: application/json

{
    "content": "content updated"
}

###

GET http://localhost:3000/comments/697395d63826c8eaa931bd2c

###

DELETE http://localhost:3000/comments/697395d63826c8eaa931bd2c

###

GET http://localhost:3000/comments/post/697394c23826c8eaa931bd2a

